
project:
    name: My Project
    #logo:
        #path: <add logo filename here>
        #width: 150

modules:
    - git: https://github.com/topcoat-data/topcoat-public.git
      revision: main

#connections:
    # Configure your connection details here then add secret to Admin/Secrets

    #- name: bigquery
    #  type: bigquery
    #  dataset: mydataset
    #  dbt: false

    #- name: postgres
    #  type: postgres
    #  host: <host address>
    #  database: <db name>
    #  port: 5432
    #  username: <username>
    #  schema: <schema>
    #  dbt: false

    #- name: snowflake
    #  type: snowflake
    #  account: <account>.<region>
    #  username: <username>
    #  warehouse: <warehouse>
    #  database: <database>
    #  schema: <schema>
    #  dbt: false

layers:
  personas: [ 'default' ]
  connection: <connection_name>

personas:
    default:
        - url: ncaa_team
          src: ncaa_team.html
          title: NCAA Teams
          icon_class: fas fa-basketball-ball

        - url: page1
          src: page1.html
          title: Page 1
          icon_class: fa-home

        - url: page2
          src: page2.html
          title: Page 2
          icon_class: fa-chart-bar

develop:
  defaults:
    filters:
      team_name: '49ers'
      season: '2015'
      year: '2020'